{% set name = "setfit" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/setfit-{{ version }}.tar.gz
  sha256: 751b9dc45023d0006c34f8e432cd7b1a83c3a5bc7d573665a0961ecd0db450f4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - datasets >=2.3.0
    - sentence-transformers >=2.2.1
    - evaluate >=0.3.0

test:
  imports:
    - setfit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SetFit/setfit
  summary: Efficient few-shot learning with Sentence Transformers
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mediocretech
