{% set name = "setfit" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/setfit-{{ version }}.tar.gz
  sha256: db54a7b6e86118343275cc70c39749f71e10aa226fef510543bcd7c8b00b9f19

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - datasets >=2.3.0
    - sentence-transformers >=2.2.1
    - evaluate >=0.3.0
    - transformers >=4.32.0

test:
  imports:
    - setfit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/SetFit/setfit
  summary: Efficient few-shot learning with Sentence Transformers
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mediocretech
